# my right half doesn't work for some reason :(
OLED_ENABLE = no
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

#CUSTOM SHIFT
SRC += features/custom_shift_keys.c
