# my right half doesn't work for some reason :(
OLED_ENABLE = no
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no

DYNAMIC_MACRO_ENABLE = no
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
# KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

# REPEAT_KEY_ENABLE = yes
# TAP_DANCE_ENABLE = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

#CUSTOM SHIFT
# SRC += features/custom_shift_keys.c
